# Combining Arrays

In [9]:
#import numpy as np

# create array with vstack
from numpy import array
from numpy import vstack,hstack
# create first array
a1 = array([1,2,3])
#print(a1)
# create second array
a2 = array([4,5,6,7])
#print(a2)
# vertical stack
print(a1)
print(a2)


[1 2 3]
[4 5 6 7]


In [10]:
a3=vstack((a1,a2))
print(a3)
print(a3.shape)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

# Horizontal Stack

In [14]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
#print(a1)
# create second array
a2 = array([4,5,6,5,6,7,7])
#print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)
print(a3.dtype)

[1 2 3 4 5 6 5 6 7 7]
(10,)
int32


In [18]:
a1 = array([[1,2,3],[4,5,6]])
a2 = array([[11,22,33],[44,55,66]])

In [20]:
a1.shape

(2, 3)

In [21]:
a2.shape

(2, 3)

In [22]:
hstack((a1,a2))

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [23]:
vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [25]:
a1 = array([1,2,3])
a2 = array([[4,5,6,7],[7,8,9],[10,11,22]])
vstack((a1,a2))

array([[1, 2, 3],
       [list([4, 5, 6, 7]), list([7, 8, 9]), list([10, 11, 22])]],
      dtype=object)

In [26]:
a1[2]

3

# Index, Slice and Reshape NumPy
Arrays

1. From List to Arrays
2. Array Indexing
3. Array Slicing
4. Array Reshaping

In [16]:
#From List to Arrays
#One-Dimensional List to Array
#Two-Dimensional List of Lists to Array

# One-Dimensional List to Array

In [6]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))
data.dtype
print(data.shape)

[11 22 33 44 55]
<class 'numpy.ndarray'>
(5,)


In [7]:
data.dtype

dtype('int64')

# one-Dimensional List of Lists to nd-Array

In [8]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],[33, 44],[55, 66],[77,88]]
# array of data
print(data)
data = array(data)
print(data)
print(type(data))
print(data.shape)

print(data[:2,:1])

[[11, 22], [33, 44], [55, 66], [77, 88]]
[[11 22]
 [33 44]
 [55 66]
 [77 88]]
<class 'numpy.ndarray'>
(4, 2)
[[11]
 [33]]


# Array Indexing

# One-Dimensional Indexing

In [9]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


In [10]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[4])

55


In [11]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


# Two-Dimensional Indexing

In [12]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[2,1])

66


In [13]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[1,1])

44


# Array Slicing

# One-Dimensional Slicing

In [14]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [15]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [16]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


# Two-Dimensional Slicing

In [17]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)
print(y.shape)
print(X.shape)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]
(3,)
(3, 2)


# Split Train and Test Rows

In [19]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:2,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


# Array Reshaping

# Data Shape

In [29]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# shape of one-dimensional array

(5,)


In [31]:
data.shape[1]

IndexError: tuple index out of range

In [34]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)

[[11 22]
 [33 44]
 [55 66]]


In [33]:
data.shape[0]

3

In [35]:
data.shape[1]

2

In [36]:
data.shape[2]

IndexError: tuple index out of range

In [10]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],[33, 44],[55, 66]]
# array of data
data = array(data)
print( ' Rows:  ' , data.shape[0])
print( ' Cols:  ', data.shape[1])
data.shape

 Rows:   3
 Cols:   2


(3, 2)

# Reshape 1D to 2D Array

In [15]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
print(data)
# reshape
data1 = data.reshape((data.shape[0],1))
print(data1.shape)
print(data1)

(5,)
[11 22 33 44 55]
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


In [37]:
data = array([11, 22, 33, 44, 55])
print(data)
print(data.shape)

[11 22 33 44 55]
(5,)


In [38]:
data1=data.reshape(data.shape[0],1)
print(data1)

[[11]
 [22]
 [33]
 [44]
 [55]]


In [39]:
data1.shape

(5, 1)

In [42]:
data2=data1.reshape((data1.shape[0],data1.shape[1],1))
print(data2)

[[[11]]

 [[22]]

 [[33]]

 [[44]]

 [[55]]]


In [43]:
data2.shape

(5, 1, 1)

# Reshape 2D to 3D Array

In [18]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],[33, 44],[55, 66]]
print(data)
# array of data
data = array(data)
print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1],1))
print(data.shape)
print(data)

[[11, 22], [33, 44], [55, 66]]
[[11 22]
 [33 44]
 [55 66]]
(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
