# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
x = np.random.random((3,3,3))
x

array([[[1.95545455e-01, 6.57485870e-02, 6.69714641e-02],
        [1.02185235e-01, 8.83969840e-01, 7.98733770e-01],
        [8.45639599e-01, 4.82174518e-04, 2.95647969e-01]],

       [[2.33401669e-01, 5.45291398e-02, 1.73841439e-01],
        [6.97941008e-01, 4.57855611e-01, 1.33543282e-01],
        [5.11511856e-01, 4.41020855e-01, 2.85771393e-01]],

       [[9.76504523e-02, 2.06133133e-01, 2.71472065e-01],
        [4.29704866e-01, 9.77678390e-02, 1.53834584e-01],
        [6.82835584e-01, 5.51071729e-01, 9.79026289e-01]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
x = np.diag(1+np.arange(4), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [12]:
x = np.random.random((5,5))
x = (x - np.mean (x) / (np.std (x)))
print(x)

[[-1.77204914 -1.3081418  -1.19825945 -1.37139417 -1.86118379]
 [-1.13749746 -1.51523413 -1.74715555 -0.99312072 -1.48345272]
 [-1.53915396 -1.6131959  -1.30110232 -1.81983084 -0.87824723]
 [-0.92338596 -0.8767918  -1.37201298 -1.21646502 -1.00904543]
 [-1.26504415 -0.99941632 -1.10112663 -1.34049706 -1.5251539 ]]


# 5.  How to find common values between two arrays?

In [14]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[3 4 6 7 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
yestardy = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tommorow = np.datetime64('today') + np.timedelta64(1)
print(yestardy)
print(today)
print(tommorow)

2020-07-31
2020-08-01
2020-08-02


# 7. Consider two random array A and B, check if they are equal

In [18]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.allclose(a,b)
print(equal)

equal = np.array_equal(a,b)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [20]:
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

[0.12788296 0.33274279 0.         0.44445729 0.44783753 0.11049583
 0.81170073 0.25126268 0.42681309 0.33808044]


# 9. How to print all the values of an array?

In [21]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [23]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.48736906  0.25083309  0.04326947 -0.23897905  0.33947787  0.4213874
  -0.34319588 -0.42873466 -0.04097625 -0.49045104]
 [ 0.27601704 -0.39176233  0.09085685 -0.14174364 -0.50590096  0.3565913
  -0.2185488   0.21044629  0.12085177  0.20319249]
 [-0.230977    0.3375782   0.28796476  0.10034572  0.08812638 -0.32856432
  -0.19843107  0.09923175 -0.19804818  0.04277374]
 [ 0.42386908  0.40080701 -0.42208812 -0.14104633 -0.34694186  0.37096356
  -0.09907462  0.11516038 -0.01234607 -0.28930303]
 [ 0.33604136  0.20634961 -0.4263528  -0.28452319  0.3520214   0.25548574
  -0.24433257 -0.23799099  0.38150781 -0.33820637]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [25]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 2. 1. 6. 4. 2. 4. 2. 4.]


In [26]:
np.add.at(Z, I, 1)
print(Z)

[ 5.  3.  3.  1. 11.  7.  3.  7.  3.  7.]


# 12.How to get the diagonal of a dot product?

In [27]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.72993688 0.60766337 0.4205894  0.3661168  0.0835208 ]
 [0.53247904 0.86879881 0.46059552 0.97380974 0.68596065]
 [0.2685072  0.33132855 0.25033476 0.63936996 0.01419904]
 [0.27260318 0.82839523 0.24540944 0.15757323 0.56434876]
 [0.37960233 0.56261673 0.73727526 0.50826225 0.97547186]]
[[0.7634999  0.70435967 0.61982895 0.45398525 0.46358976]
 [0.25138459 0.15778608 0.26164413 0.08869834 0.48637749]
 [0.89371127 0.08032626 0.58352936 0.33721382 0.54649063]
 [0.42557942 0.20624146 0.0123864  0.31379585 0.64108592]
 [0.78070102 0.90053415 0.95204521 0.16700762 0.85417946]]
diagonal of a dot product method 1 is.... [1.30696598 1.36770996 0.42063401 0.42368693 2.01160568]
diagonal of a dot product method 2 is.... [1.30696598 1.36770996 0.42063401 0.42368693 2.01160568]


# 13.How to find the most frequent value in an array?

In [28]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[0 3 0 7 0 6 0 0 8 6 5 3 4 3 2 5 1 6 1 1 6 0 6 6 3 2 7 5 4 5 7 7 7 6 2 1 6
 8 3 2 1 7 3 4 6 5 5 3 8 2]
6


# 14.How to get the n largest values of an array

In [29]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [30]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
